# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install: 
  - pip install coveralls
  - pip install .
# command to run tests
script: coverage run --source ndex_webapp_python_exporters setup.py test

after_success: coveralls
